// Bundled list of major US cities for offline location autofill.
// Format: "City, ST". Enough coverage for the MVP without a Places API.
export const US_CITIES: string[] = [
  "New York, NY", "Los Angeles, CA", "Chicago, IL", "Houston, TX",
  "Phoenix, AZ", "Philadelphia, PA", "San Antonio, TX", "San Diego, CA",
  "Dallas, TX", "San Jose, CA", "Austin, TX", "Jacksonville, FL",
  "Fort Worth, TX", "Columbus, OH", "Charlotte, NC", "San Francisco, CA",
  "Indianapolis, IN", "Seattle, WA", "Denver, CO", "Washington, DC",
  "Boston, MA", "El Paso, TX", "Nashville, TN", "Detroit, MI",
  "Oklahoma City, OK", "Portland, OR", "Las Vegas, NV", "Memphis, TN",
  "Louisville, KY", "Baltimore, MD", "Milwaukee, WI", "Albuquerque, NM",
  "Tucson, AZ", "Fresno, CA", "Sacramento, CA", "Mesa, AZ",
  "Kansas City, MO", "Atlanta, GA", "Omaha, NE", "Colorado Springs, CO",
  "Raleigh, NC", "Long Beach, CA", "Virginia Beach, VA", "Miami, FL",
  "Oakland, CA", "Minneapolis, MN", "Tulsa, OK", "Bakersfield, CA",
  "Wichita, KS", "Arlington, TX", "Aurora, CO", "Tampa, FL",
  "New Orleans, LA", "Cleveland, OH", "Honolulu, HI", "Anaheim, CA",
  "Lexington, KY", "Stockton, CA", "Corpus Christi, TX", "Henderson, NV",
  "Riverside, CA", "Newark, NJ", "Saint Paul, MN", "Santa Ana, CA",
  "Cincinnati, OH", "Irvine, CA", "Orlando, FL", "Pittsburgh, PA",
  "St. Louis, MO", "Greensboro, NC", "Jersey City, NJ", "Anchorage, AK",
  "Lincoln, NE", "Plano, TX", "Durham, NC", "Buffalo, NY",
  "Chandler, AZ", "Chula Vista, CA", "Toledo, OH", "Madison, WI",
  "Gilbert, AZ", "Reno, NV", "Fort Wayne, IN", "North Las Vegas, NV",
  "St. Petersburg, FL", "Lubbock, TX", "Irving, TX", "Laredo, TX",
  "Winston-Salem, NC", "Chesapeake, VA", "Glendale, AZ", "Garland, TX",
  "Scottsdale, AZ", "Norfolk, VA", "Boise, ID", "Fremont, CA",
  "Spokane, WA", "Santa Clarita, CA", "Baton Rouge, LA", "Richmond, VA",
  "Hialeah, FL", "San Bernardino, CA", "Tacoma, WA", "Modesto, CA",
  "Huntsville, AL", "Des Moines, IA", "Yonkers, NY", "Rochester, NY",
  "Moreno Valley, CA", "Fayetteville, NC", "Fontana, CA", "Columbus, GA",
  "Worcester, MA", "Port St. Lucie, FL", "Little Rock, AR", "Augusta, GA",
  "Oxnard, CA", "Birmingham, AL", "Montgomery, AL", "Frisco, TX",
  "Amarillo, TX", "Salt Lake City, UT", "Grand Rapids, MI", "Huntington Beach, CA",
  "Overland Park, KS", "Knoxville, TN", "Providence, RI", "Brownsville, TX",
  "Tonasket, WA", "Bellingham, WA", "Eugene, OR", "Salem, OR",
  "Tallahassee, FL", "Fort Collins, CO", "Springfield, MO", "Savannah, GA",
];
